### ISSUE TITLE
Let me try something out

### ISSUE THREAD

**Issue by Hocceruser** [Hocuri/BetterIlias#1]
Just testing github notification emails. @Hocuri 

(lol just noticed that one person is actually watching this repo. Rather watch https://github.com/Septias/BetterIlias)

**Comment by Hocuri** [comment]
This message is sent from Delta Chat!

--
Sent with my Delta Chat Messenger: https://delta.chat

**Comment by Hocuri** [comment]
> This message is sent from Delta Chat!

Trying out quotes...

--
Sent with my Delta Chat Messenger: https://delta.chat

**Comment by Hocceruser** [comment]
:tada:
